spring:
  application:
    name: task-tracker
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:root}:${MONGODB_PASSWORD:root}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DBNAME:appdatabase}?authSource=admin

server:
  port: ${APP_SERVER_PORT:8080}